blank_issues_enabled: false
contact_links:
  - name: Module Documentation
    url: 'https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-reporting'
    about: Having trouble with the module? Check out the documentation.
  - name: VMware Cloud Foundation Product Documentation
    url: https://vmware.com/go/vcf-docs
    about: Manage VM and container-based workloads with the hybrid cloud platform, built on full stack hyper-converged infrastructure.
