blank_issues_enabled: false
contact_links:
  - name: VMware Cloud Foundation Product Documentation
    url: https://vmware.com/go/vcf-docs
    about: Manage VM and container-based workloads with the hybrid cloud platform, built on full stack hyper-converged infrastructure.
